### ISSUE TITLE
Why not censor all functions, or at least cross‑module functions?

### ISSUE THREAD

**Issue by ExE-Boss** [domenic/proposal-function-prototype-tostring-censorship#12]
IMHO, the result of calling `Function.prototype.toString()` on non‑native implementations is a bafflingly dumb idea, as it reveals the inner workings of third party code, which should’ve been encapsulated.

This issue would make it so that the inner workings of all functions would be hidden, thus avoiding the concerns of #10 and #3 entirely.

**Comment by domenic** [comment]
This sounds like a separate proposal, that would have different semantics and consequences to this proposal. For example, it seems backward-incompatible with the current web. Is that correct?

**Comment by ExE-Boss** [comment]
> For example, it seems backward-incompatible with the current web. Is that correct?

Possibly.

**Comment by domenic** [comment]
OK. I'm not interested in championing a proposal that would be backward-incompatible with the web today, so I'll close this.
